### ISSUE TITLE
Erro no Watch

### ISSUE THREAD

**Issue by eduardoborges** [eduardoborges/base-angularjs#1]
Existe um erro no watch de injetar os arquivos do projeto.
Na função serveTask() o watch parece parar as vezes.
A função Inject só funciona na primeira vez, ao modificar não injeta mais :/

**Comment by diegomelo182** [comment]
@eduardoborges veja isso e substitua no seu projeto, funciona muito bem comigo ;)
https://www.npmjs.com/package/gulp-main-bower-files

**Comment by eduardoborges** [comment]
Bem, eu imagino que seja no inject mesmo. Mas vou testar,
